### ISSUE TITLE
Provide a GSettings interface to dark style preference

### ISSUE THREAD

**Issue by danrabbit** [elementary/settings-daemon#16]
We need to use AccountsService as a source of truth for the greeter, but it would be better for apps to be able to read a gsetting (and it sounds like this is especially true in Flatpak). It also sounds like the Epiphany team would be cool with reading our dark style key if it was a gsetting

**Comment by cassidyjames** [comment]
Something we need to be super clear about for apps: they should not (intentionally or accidentally) modify this GSetting. They should only read from it, or just use the Granite util where we could ensure it is read-only.

**Comment by davidmhewitt** [comment]
Yeah I'm sure we can make sure that if it is modified that it just gets set back to whatever the current accountsservice value is.

**Comment by danrabbit** [comment]
This should be enforced by flatpak apps automatically as well, I think

**Comment by cassidyjames** [comment]
So @tintou had doubts that this would work for Flatpak apps in standup today, so we should confirm that this is the right way to go. To clarify, the basic idea is to mirror the AccountsService setting somewhere readable by Flatpak apps so that i.e. Epiphany and eventually flatpaked AppCenter apps can hook off of it without needing to use AccountsService or probably even the Granite util (which uses AccountsService).

**Comment by davidmhewitt** [comment]
Recent relevant discussion here: https://gitlab.gnome.org/GNOME/glib/-/issues/2213

**Comment by danrabbit** [comment]
So then maybe what we actually want is to provide a DBus endpoint and we can change the granite class to read the dbus endpoint of elementary settings daemon

**Comment by danrabbit** [comment]
Sounds like the plan is to add a DBus endpoint at `org.freedesktop.prefers-color-scheme` with the same 0, 1, 2 as we do currently in accountsservice

**Comment by Marukesu** [comment]
i think that we need to expose the gsettings scheme via the settings portal and update the granite function to read from it when inside a flatpak sandbox.

**Comment by davidmhewitt** [comment]
> Sounds like the plan is to add a DBus endpoint at `org.freedesktop.prefers-color-scheme` with the same 0, 1, 2 as we do currently in accountsservice

I can't remember for sure, but isn't there something about using hyphens in dbus names that's generally ill-advised?

**Comment by danrabbit** [comment]
@davidmhewitt ah I don't remember. It does seem that most other services are preferring CamelCase

**Comment by WhyNotHugo** [comment]
Hi! I'm currently working on bringing dark mode to my own desktop with a pile of different apps from different sources. Since you guys are quite advanced on this topic, I'd like my implementation to be compatible (albeit, targeting non-elementary desktops). Hopefully others will follow suit and applications will be nice and compatible across desktops :crossed_fingers: 

Based on the above discussion, I see that the service name is still fully defined. This has to be consistent across all services (e.g.: if other desktops implement a daemon that exposes the same API, it needs to expose it under the same name). Might I suggest `org.freedesktop.ColorScheme`?

The convention for D-Bus is generally CamelCase, yes. I believe these would best-match current conventions, and cover the needs of all sorts of applications and scenarios:

- The method to change the setting should be `SetPreferredColorScheme`.
- The signal to notify listener that the setting has changed should be `PreferredColorSchemeChanged`.
- The property to read the current value of the setting should be `PreferredColorScheme`.

**Comment by cassidyjames** [comment]
Okay, after lots of discussion and a meeting, we're going to go ahead with a GSetting for this. The AccountService DBus endpoint will remain on elementary OS so we can integrate with the greeter, but we'll mirror that setting to a GSetting so that Flatpak apps can read and respond to it.

**Comment by WhyNotHugo** [comment]
I'm not very happy with this news.

D-Bus is very standard and ubiquitous on Linux desktop. I'm already working on a standalone D-Bus daemon (to be used outside Elementary OS), and I'd love if two parties in the ecosystem had compatible goals.

D-Bus services can be perfectly exposed to Flatpak. `org.freedesktop.Notifications` is an incredibly common example of this. I'm happy to elaborate further on this.

OTOH, exposing gsettings into Flatpak apps is very painful on many environments. Users of `sway`, `i3` and many other non-DE environments already frequently have issues due to gsettings not playing well with Flatpak apps (given they're not using the gnome portal).

Could this still be open for discussion? I actually see no discussion on this thread; the last message prior was my own.

**Comment by cassidyjames** [comment]
@WhyNotHugo honestly I'm not personally knowledgeable enough to communicate the precise reasoning, and part of the issue is having a back-and-forth discussion like this for months in multiple places. I am simply updating here what has been discussed within elementary and with folks from Flatpak and GNOME. 

I think theoretically this is still open to change, but honestly this is one of the last few things preventing an elementary OS 6 beta; I would like to get it sorted ASAP. Ultimately there is little harm to app developers targeting elementary OS if things change, as we can update Granite to do the right thing under-the-hood. But we need to ship _something_ that is usable by third-party apps, GNOME apps, and Flatpak apps on elementary OS if we are to ship a beta—and from my understanding, a GSetting satisfies that to our satisfaction.

**Comment by WhyNotHugo** [comment]
> what has been discussed within elementary and with folks from Flatpak and GNOME.

This is my point: the solution works fine on gnome, but not on many non-gnome desktops. D-Bus is far simpler, works equally well in Gnome, but _also_ works very well in many other environments.

Given that I posted two months ago showing interest in aligning our goals and proposing a solution, I would have appreciated being let know if this discussion had been going elsewhere.

I'm clearly hear to contribute, yet it seems that discussions happen elsewhere?

> Ultimately there is little harm to app developers targeting elementary OS if things change

Actually, there is harm: it immediately creates a fragmented ecosystem. I've been adding support for the D-Bus tooling elsewhere, and both our implementations would be incompatible for app developers.

**Comment by cassidyjames** [comment]
>the solution works fine on gnome, but not on many non-gnome desktops. D-Bus is far simpler, works equally well in Gnome, but also works very well in many other environments.

With our stack, GSettings is a lot simpler to hook into in my experience than DBus—plus it's going to be simpler and more familiar to GNOME developers who are very interested in shipping this feature as well. GSettings being more specific to GNOME, its dowstreams, and elementary OS is an understandable concern, and if we can get some wider consensus down the line, then we can adapt.

>I would have appreciated being let know if this discussion had been going elsewhere. I'm clearly hear to contribute, yet it seems that discussions happen elsewhere?

The conversation has been happening in parallel from several interested parties across multiple projects on the elementary issue tracker, GNOME GitLab, IRC, Slack, and probably a handful of other places. The problem has been having no real consensus from all parties, because each party has a different reason they are _undeniably right._ Instead of getting stalled there at the moment, we've made the decision to try a GSetting on elementary OS for now to get help get the beta out the door sooner. There's no conspiracy of us taking the discussion elsewhere to exclude anyone, just that there was never a single canonical discussion in the first place. Since this issue report is the actionable item on the elementary issue tracker, I'm using it to provide a summary of the happenings from elsewhere to make some forward progress. Otherwise this will remain in discussion across different places in perpetuity, or everyone will just go do their own thing anyway and we will still not have a solution for our app developers.

>>there is little harm to app developers targeting elementary OS

>Actually, there is harm: it immediately creates a fragmented ecosystem. I've been adding support for the D-Bus tooling elsewhere, and both our implementations would be incompatible for app developers.

Developers targeting elementary OS will not be accessing a DBus API or GSetting directly, they will be using Granite and its preexisting API for this—that's my point. So, **for developers targeting elementary OS, there is little harm if things change under-the-hood** as we will update Granite to do whatever we land on for the stable release. The important thing here for our release process is that the Granite API does not change out from under developers after the beta, which it won't no matter if we're talking to GSettings or DBus or keyfiles or whatever.

So yeah. This could change directions, _yet again,_ based on feedback from app developers, Flatpak folks, GNOME folks, GTK folks, etc. But I'm at least going to propose some code here so we can begin trying it out instead of it staying in discussion forever. If an alternate solution—yours, or someone else's—gains more traction from developers, we can always revisit it to remain compatible and align on a cross-desktop solution.

If someone else from @elementary/desktop-developers could chime in on the more technical reason(s) for GSettings over DBus, it would be appreciated. Again, _I do not personally care_ how it is implemented, just that it is implemented, works in third-party apps targeting elementary OS, works in Flatpaks on elementary OS, and is acceptable to GNOME. GSettings gets us there today. We can change it under-the-hood tomorrow for all I care. :smile:

**Comment by WhyNotHugo** [comment]
> The AccountService DBus endpoint will remain on elementary OS so we can integrate with the greeter

What, this confuses me a bit. The greeter runs _before_ the user logs in, so there's no per-user dbus server alive yet.

I hope this won't be the _system_ D-Bus, since this is a per-user service. Each user could, potentially, have its own instance with its own settings.

**Comment by cassidyjames** [comment]
@WhyNotHugo dark style is already implemented in elementary OS 6 via AccountsService, where the greeter can read user preferences before logging in. I'm not 100% sure how it works in detail, but it's how we also handle other things like per-user profile pictures, wallpapers, and even keyboard layouts. The idea being that we can draw the greeter to match the user's preference so they get a more seamless login, and then if you switch users in the greeter, we can update the greeter to follow that selected user's preferences on the fly. This is implemented in elementary OS 6 today, and is what Granite talks to—and thus how our first-party apps already respond to the preference. However, there were concerns around exposing AccountsService to Flatpaks and third-party apps, so we are mirroring this preference elsewhere that _is_ accessible to those apps, and then will update Granite to talk to that instead.

AccountsService will remain the "source of truth" for now, and is how the System Settings sets the preference. The GSetting will be treated as read-only (enforced by the elementary Settings Daemon), and is an easier way for apps to listen and respond to the user's preference.

**Comment by WhyNotHugo** [comment]
I see.

It seems that we have, ultimately, incompatible goals, since you're running a system service to handle dark mode, whereas I'm working on a user-service to handle this at a per-user level..

I seems applications supporting one dark mode interface won't be able to support the other. This makes quite rather sad though: elementary/gnome applications won't pick up dark mode properly on other environments, and apps tailored to work with `darkman` won't pick up dark mode in elementary or gnome.

Thanks for the updates, it's a shame we could not coordinate something interoperable here.

Cheers!

**Comment by Exalm** [comment]
> These scripts individually configure different components and applications. Given the
lack of normalised "dark-mode" APIs on Linux desktop, it's likely that scripts for
different applications and toolkits have to be dumped in.

Seems it's incompatible here already. elementary and GNOME don't want to and won't ship scripts for third-party apps; our goal is to provide API _for_ those apps, so that they can support it ithemselves. And given this, I don't see why darkman couldn't flip the desktop-wide preference from here.

**Comment by WhyNotHugo** [comment]
`darkman` has three goals:

1. Executed certain scripts to switch application to dark mode (e.g.: change the terminal's theme). This is for applications that don't natively support dark mode yet.
2. Expose a D-Bus interface for application that want first-class dark mode. This API can be used by any application that wants to follow the user's dark-mode preference.
3. Allows auto-changing dark-mode on and off based on the sunrise/sundown time of the user.

It's item (2) that I wish we could align on so that it can be standardised across desktops.

> And given this, I don't see why darkman couldn't flip the desktop-wide preference from here.

I guess that changing the value of the GSetting would be possible (in just one of those drop-in scripts). But not if it's defined as a read-only property.

**Comment by Exalm** [comment]
It could access accountmanager too. If Swichboard can do it, why not darkman?

As for the goals, I don't think it should do 2. That's just fragmentation, imagine e.g. Firefox supporting only it, that doesn't help anybody.

**Comment by WhyNotHugo** [comment]
> It could access accountmanager too. If Swichboard can do it, why not darkman?

Because I'm not running `AccountManager`. Like I said, I'm not on Elementary OS.

> As for the goals, I don't think it should do 2. That's just fragmentation, imagine e.g. Firefox supporting only it, that doesn't help anybody.

There's nothing else I can use on my desktop. There's currently no API for application to determine dark mode, and I'm writing a D-Bus interface since that can run anywhere.

This fragmentation is _exactly_ why I joined this discussion a couple of months ago, since I'd like to prevent having that.

**Comment by danrabbit** [comment]
@WhyNotHugo AccountsService is our source of truth so that we can expose user information to the greeter, but it is per user information :) 

I would advise you to go ahead along the dbus endpoint route even though that would make things a bit fragmented for now, because if we can get enough 3rd party developers on board with it we can always add a DBus endpoint to elementary settings daemon and switch Granite over to listening to it and deprecate the gsettings key, no losses for our developer community

Something to keep in mind however is that if you expose a set mechanism in your dbus interface then you will allow apps to set the system wide dark style for other apps. The API for apps should be intentionally read only so that only the user is in control here. That's why, for us AccountsService is the source of truth and gsettings is only a one-way mirror of that truth

For us right now to meet our ship goals, a gsettings API makes the most sense for the developers we need on board. That doesn't mean that it will always be this way and we can't try to change it in the future. It may be that our settings daemon will have to expose a gsettings API for GNOME and use DBus for everyone else even. I guess we'll find out. As always the hardest part of open source software is the politics 🙃

**Comment by tinywrkb** [comment]
> @WhyNotHugo honestly I'm not personally knowledgeable enough to communicate the precise reasoning, and part of the issue is having a back-and-forth discussion like this for months in multiple places. I am simply updating here what has been discussed within elementary and with folks from Flatpak and GNOME.

Were these discussions public? any link to mailing list threads? reported issues in the respected projects repos?

**Comment by Exalm** [comment]
Read only - not much point, apps can already change every other setting. The solution to that is sandboxing, not implementing separate channels for one specific preference. :) (also gsettings can't be readonly, can they?)

**Comment by cassidyjames** [comment]
@tinywrkb I don't have links off the top of my head and much of this sort of discussion in open source happens in ephemeral places like IRC, Slack, calls, or out of band discussions at conferences. This issue tracker is for the elementary Settings Daemon and is where we have chosen to document our findings and decision from the elementary side. But honestly there have been so many back-and-forth discussions with so many different people in so many places without much consensus that I can't remember what was discussed when and where.

**Comment by danrabbit** [comment]
@Exalm We're assuming we're talking about sandboxed apps here. Adding a set method to the dbus endpoint would defeat the purpose of the sandbox

The gsettings key can be read only in the sense that the only listening to its changes are the settings daemon to change it back t the correct value :p

**Comment by Exalm** [comment]
If it's sandboxed, all gsettings are readonly already.

**Comment by tinywrkb** [comment]
@cassidyjames Thanks for answering! I really hoped Elementary's effort would end up with something more generic. Maybe the right place to discuss this is in the xdg-desktop-portal issue tracker.

**Comment by cassidyjames** [comment]
@tinywrkb we are still committed to a more generic, inter-compatible preference for sure! We just also know that we need to ship a solution in practice so we can actually have a working proof of concept for our beta release, and to present to other interested parties. 

We plan to continue this work.

**Comment by WhyNotHugo** [comment]
> if we can get enough 3rd party developers on board with it we can always add a DBus endpoint to elementary settings daemon and switch Granite over to listening to it and deprecate the gsettings key, no losses for our developer community

That'd be lovely!

> Something to keep in mind however is that if you expose a set mechanism in your dbus interface then you will allow apps to set the system wide dark style for other apps. The API for apps should be intentionally read only so that only the user is in control here. That's why, for us AccountsService is the source of truth and gsettings is only a one-way mirror of that truth

I haven't defined any mechanism to change it, only to set it. This is because `darkman` automatically changes light mode / dark mode at sunrise / sunset respectively. I'm sure this'll somehow be configurable some day, but for now it's not important.

> I don't have links off the top of my head and much of this sort of discussion in open source happens in ephemeral places like IRC, Slack, calls, or out of band discussions at conferences.

This does make collaboration very hard -- especially on topics related to standardising across desktops. I hope you don't take it the wrong way if I advise to avoid these "behind close doors" decisions. These sort of issues re the perfect place for other parties to contribute to the discussion.

---

Re sandboxes: gsettings _may_ be read-only. But they may also be completely inaccessible too, since it's fairly complex to set up portals properly in other environments (the gnome portal is required for gsettings to be available, but the gnome portal breaks things like screensharing on other compositors, so one needs to fiddle with the portal a lot to make it work).

**Comment by Exalm** [comment]
I mean, it's a job of the DE to have working portals, not the user.

**Comment by WhyNotHugo** [comment]
> I mean, it's a job of the DE to have working portals, not the user. If you can't depend on that, all bets are off.

In case you're using a DE, the DE does do the setup.

For anyone not using a DE, the setup must be done manually. For example, when using `sway`, one must set up `xdg-desktop-portal-wlr` (which is fairly each, just install it and that's it).

The problem with `gsettings` is that it's exposed via the GNOME portal, but not other portals, so getting apps which depend on `gsettings` to run on non-GNOME is quite a pain (I managed to do it by hacking the gnome portal to only listen to a specific interface, but it requires messing with the portal internals itself).

`gsettings` is not standard on other desktops, so it's unlikely the situation will change.

**Comment by Exalm** [comment]
Well, in that case it doesn't really matter where it is, as long as every portal implementation exposes it from somewhere, and all apps should just use that? The portal is generic enough to not have to be gsettings.

**Comment by WhyNotHugo** [comment]
> Well, in that case it doesn't really matter where it is, as long as every portal implementation exposes it from somewhere, and all apps should just use that?

If Elementary apps try to read a gsetting, but the portal exposes a DBus API to them, then no, it won't work.

**Comment by Exalm** [comment]
Wrong. GIO automatically accesses portal when you try to read certain settings, apps don't access it manually. Qt etc likely have their own ways to access portal, and if not, it can always be accessed manually through dbus.
